### ISSUE TITLE
Restrict users who are able to dispatch deployment

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/proto_feedstock#17]
Still needs some discussion, but In general do we want to allow every recipe creator to potentiall fire off giant dataflow jobs?

here is a suggestion by chatgpt how we could potentially limit this to certain people/teams

```
name: Controlled Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  check_permission:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is authorized
        run: |
          if [[ "$GITHUB_ACTOR" != "authorized_user1" && "$GITHUB_ACTOR" != "authorized_user2" ]]; then
            echo "You are not authorized to trigger this workflow."
            exit 1
          fi

  main_job:
    needs: check_permission
    runs-on: ubuntu-latest
    steps:
      - name: Execute Main Steps
        run: echo "Running main steps..."
```
