### ISSUE TITLE
Can we autogenerate the catalog yaml paths?

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/proto_feedstock#28]
Looking at [the template catalog.yaml file](https://github.com/leap-stc/proto_feedstock/edit/main/feedstock/catalog.yaml) I suspect that there will be issues with people just not editing the paths and then stores get overwritten...

Wondering if there is an easy way to generate these paths (and maybe some other dummy content) for the catalog.yaml. 
The template for that would be something like:

```yaml
# All the information important to cataloging.
"ncviewjs:meta_yaml_url": "https://github.com/<owner>/<repo_name>/blob/main/feedstock/meta.yaml"
tags:
  - zarr
stores:
  - id: <recipe_id (parse_from_meta_yaml)>
    url: "gs://leap-scratch/data-library/feedstocks/latest/<repo_name>/<recipe_id>.zarr"
```
Not super important rn, but just putting this out there. Maybe @andersy005 has an idea?
